//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Magic.rc
//
#define ID_RESET                        3
#define IDC_NEW_MATERIAL                3
#define ID_BACK_COLOR                   4
#define IDC_DEL_MATERIAL                4
#define IDC_SELECT_POLYS                5
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MAGICTYPE                   129
#define IDD_SURFACE_PROPS               130
#define IDD_CAMERA_PROPS                131
#define IDD_MODIFY_SURFACE              135
#define IDD_VERTS_REDUCE                136
#define IDD_MODIFY_POLY                 137
#define IDD_CREATE_CUBE                 138
#define IDD_CREATE_CYLINDER             139
#define IDD_CREATE_SPHERE               140
#define IDD_MODIFY_TEXTURE              141
#define IDD_GRIDPROPS                   142
#define IDD_MODIFY_POLYS                143
#define IDD_CREATE_POLY                 144
#define IDD_EXTRUSION_PROPS             146
#define IDD_MODIFY_MATERIAL             147
#define IDC_SURFACE_NAME                1000
#define IDC_SURFACE_NVERTS              1001
#define IDC_SURFACE_NPOLYS              1002
#define IDC_SURFACE_COLOR               1003
#define IDC_SURFACE_RADIUS              1003
#define IDC_SURFACE_LENGTH              1004
#define IDC_SURFACE_WIDTH               1005
#define IDC_CAMERA_DISTANCE             1006
#define IDC_SURFACE_HEIGHT              1006
#define IDC_CAMERA_FOV                  1007
#define IDC_CAMERA_MODE                 1008
#define IDC_SURFACE_LIST                1009
#define IDC_SURF_NAME                   1010
#define IDC_SURF_POLYS                  1011
#define IDC_SURF_COLOR                  1012
#define IDC_SURF_HIDDEN                 1013
#define IDC_SURF_LOCKED                 1014
#define IDC_SURF_CREATE                 1015
#define IDC_SURF_DISCARD                1016
#define IDC_SURF_CLONE                  1017
#define IDC_SURF_DELETE                 1018
#define IDC_SURF_ADD_POLYS              1019
#define IDC_THRESHOLD                   1020
#define IDC_SURF_ID                     1020
#define IDC_FLATTEN                     1021
#define IDC_FLIP_NORM                   1022
#define IDC_DOUBLE_SIDE                 1023
#define IDC_TRIANGULATE                 1024
#define IDC_REMOVE                      1025
#define IDC_POLY_VERTS                  1026
#define IDC_POLY_X                      1027
#define IDC_POLY_Y                      1028
#define IDC_POLY_Z                      1029
#define IDC_POLY_CURVE                  1030
#define IDC_POLY_SURF                   1031
#define IDC_POLY_TEX                    1032
#define IDC_LOC_X                       1033
#define IDC_LOC_Y                       1034
#define IDC_LOC_Z                       1035
#define IDC_SIZE_X                      1036
#define IDC_SIZE_Y                      1037
#define IDC_SIZE_Z                      1038
#define IDC_SECTORS                     1039
#define IDC_RINGS                       1040
#define IDC_GRID_SNAP                   1041
#define IDC_TEXTURE                     1041
#define IDC_MATERIAL                    1041
#define IDC_GRID_SIZE                   1042
#define IDC_MAPPING                     1042
#define IDC_GRID_SHOW                   1043
#define IDC_ALIGN_X                     1043
#define IDC_GRID_LINES                  1044
#define IDC_ALIGN_Y                     1044
#define IDC_GRID_DOTS                   1045
#define IDC_ALIGN_Z                     1045
#define IDC_SCALE_U                     1046
#define IDC_SCALE_V                     1047
#define IDC_TEXTURE_ADD                 1048
#define IDC_TEXTURE_DELETE              1049
#define IDC_ALIGN_FLIP                  1050
#define IDC_ALIGN_MIRROR                1051
#define IDC_ALIGN_ROTATE                1052
#define IDC_TEXTURE_RELOAD              1053
#define IDC_TEXTURE_PREVIEW             1054
#define IDC_TEMPLATE                    1055
#define IDC_AMBIENT_COLOR               1055
#define IDC_FLAG_FLAT                   1056
#define IDC_DIFFUSE_COLOR               1056
#define IDC_FLAG_LUMINOUS               1057
#define IDC_NSIDES                      1057
#define IDC_SPECULAR_COLOR              1057
#define IDC_FLAG_TRANSLUCENT            1058
#define IDC_EMISSIVE_COLOR              1058
#define IDC_FLAG_TRANSPARENT            1059
#define IDC_SECONDARY                   1059
#define IDC_FLAG_SPECULAR               1060
#define IDC_FLAG_FLAT2                  1061
#define IDC_FLAG_LUMINOUS2              1062
#define IDC_POLY_INDEX                  1062
#define IDC_FLAG_TRANSLUCENT2           1063
#define IDC_FLAG_TRANSPARENT2           1064
#define IDC_FLAG_SPECULAR2              1065
#define IDC_FLAG_TEXCLAMP               1066
#define IDC_DISTANCE                    1067
#define IDC_FLAG_SPECULAR22             1067
#define IDC_FLAG_SPECULAR1              1068
#define IDC_FLAG_SPECULAR12             1069
#define IDC_FLAG_TEXCLAMP2              1070
#define IDC_MATERIAL_LIST               1070
#define IDC_MATERIAL_NAME               1071
#define IDC_DIFFUSE_TEXTURE             1072
#define IDC_SPECULAR_TEXTURE            1073
#define IDC_EMISSIVE_TEXTURE            1074
#define IDC_BUMP_TEXTURE                1075
#define IDC_AMBIENT_VALUE               1076
#define IDC_DIFFUSE_VALUE               1077
#define IDC_SPECULAR_VALUE              1078
#define IDC_EMISSIVE_VALUE              1079
#define IDC_BUMP_VALUE                  1080
#define IDC_POWER_VALUE                 1081
#define IDC_BRILLIANCE_VALUE            1082
#define IDC_BLEND_MODE                  1083
#define IDC_MATERIAL_PREVIEW            1084
#define IDC_FILE_DIFFUSE                1085
#define IDC_FILE_SPECULAR               1086
#define IDC_REFERENCE_PLAN              1086
#define IDC_FILE_EMISSIVE               1087
#define IDC_REFERENCE_SIDE              1087
#define IDC_FILE_BUMP                   1088
#define IDC_REFERENCE_FRONT             1088
#define IDC_SHADOW                      1089
#define IDC_FILE_PLAN                   1090
#define IDC_MATERIAL_SHADER             1090
#define IDC_FILE_SIDE                   1091
#define IDC_FILE_FRONT                  1092
#define ID_GRID_PROPS                   32771
#define ID_VIEW_ZOOM_IN                 32771
#define ID_VIEW_ZOOM_OUT                32772
#define ID_VIEW_ZOOM_NORMAL             32773
#define ID_VIEW_CENTER                  32774
#define ID_SURFACE_CREATE               32779
#define ID_MODIFY_DRAG_VERTS            32780
#define ID_CREATE_CUBE                  32781
#define ID_CREATE_TETRA                 32782
#define ID_MODIFY_EXTRUDE               32784
#define ID_MODIFY_BEVEL                 32785
#define ID_MODIFY_STUD                  32786
#define ID_MODIFY_SUBDIVIDE             32787
#define ID_PROP_SURFACE                 32788
#define ID_PROP_CAMERA                  32789
#define ID_EDIT_FLIP_NORMAL             32790
#define ID_EDIT_REMOVE_POLY             32791
#define ID_EDIT_MERGE_POLY              32792
#define ID_MODIFY_TEXTURE               32795
#define ID_OPTIONS_VERTEX_NORMALS       32798
#define ID_PROP_GRID                    32800
#define ID_EDIT_DELETE                  32801
#define ID_CREATE_POLY                  32802
#define ID_CREATE_VERT                  32803
#define ID_CREATE_CYLINDER              32804
#define ID_CREATE_SPHERE                32805
#define ID_FILE_IMPORT                  32806
#define ID_FILE_EXPORT                  32807
#define ID_MODIFY_POLY                  32808
#define ID_MODIFY_VERTS                 32809
#define ID_VERTS_REDUCE                 32810
#define ID_VERTS_SNAP                   32811
#define ID_MODIFY_SCALE_VERTS           32812
#define ID_MODIFY_ROTATE                32813
#define ID_CREATE_CONE                  32814
#define ID_FINAL_RENDER                 32815
#define ID_MODIFY_SCALE_X               32817
#define ID_MODIFY_SCALE_Z               32819
#define ID_MODIFY_SCALE_Y               32822
#define ID_MODIFY_SPLIT1                32824
#define ID_MODIFY_SPLIT2                32825
#define ID_EDIT_MIRROR                  32826
#define ID_EDIT_SEAL                    32827
#define ID_EDIT_CLONE                   32828
#define ID_GRID_SNAP                    32829
#define ID_MODIFY_FLATTEN_X             32830
#define ID_MODIFY_FLATTEN_Y             32831
#define ID_MODIFY_FLATTEN_Z             32832
#define ID_EDIT_SELECT_NONE             32833
#define ID_NUDGE_RIGHT                  32834
#define ID_NUDGE_LEFT                   32835
#define ID_NUDGE_UP                     32836
#define ID_NUDGE_DOWN                   32837
#define ID_STEP_LEFT                    32838
#define ID_STEP_RIGHT                   32839
#define ID_STEP_UP                      32840
#define ID_STEP_DOWN                    32841
#define ID_VIEW_RENDER                  32842
#define ID_VIEW_ALL                     32843
#define ID_VIEW_FRONT                   32844
#define ID_VIEW_SIDE                    32845
#define ID_VIEW_TOP                     32846
#define ID_VIEW_PERSPECTIVE             32847
#define ID_MODIFY_TEXTURE_MAP           32848
#define ID_MODIFY_MATERIAL              32849
#define ID_VIEW_MODE_WIREFRAME          32850
#define ID_VIEW_MODE_SOLID              32851
#define ID_VIEW_MODE_TEXTURED           32852
#define ID_GRID_SHOW                    32853
#define ID_VIEW_BACK_COLOR              32854
#define ID_EDIT_SELECT_INVERSE          32855
#define ID_MODIFY_UV_MAP                32856
#define ID_VIEW_SHADOWS                 32857
#define ID_VIEW_ANIMATELIGHT            32858
#define ID_VIEW_BUMPMAPS                32859
#define ID_VIEW_VERTEXSHADER            32860
#define ID_VIEW_PIXELSHADER             32861
#define ID_VIEW_VISIBLESHADOWS          32862
#define ID_SURFACE_OPTIMIZE             32863
#define ID_SURFACE_EXPLODE              32864

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32865
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
